### ISSUE TITLE
Format for IE8 

### ISSUE THREAD

**Issue by amccann1** [hanami/controller#167] opened 2016-07-29 10:47 UTC
Hi 
I posted this in the hanami chat posting here for collecting all information;

I was wondering if someone can give me a little pointer here as I’m not familiar with how the self.format is being selected.

My app works fine in most browsers and gets the format :html matching text/html from the HTTP_ACCEPT except in IE8.

It keeps requesting :jpeg with the error

`Hanami::View:MissingTemplateError: Can’t find template ’signup/new’ for ‘jpeg’ format.`

Since IE8 has `*/*` at the end of its HTTP_ACCEPT should it not also get :html?

I saw the issue [#104](https://github.com/hanami/controller/issues/104) raised for wrong IE format and the fix [#105](https://github.com/hanami/controller/pull/105)
This was added to version 0.4.0, I have version 0.6.1 running.

I tried to debug `best_q_match` in  `lib/lotus/action/mime.rb`it seems like `*/*` is being resolved as `application/vnd.lotus-1-2-3`, since it is the first in the list of available mime types.

**Comment by amccann1** [comment] 2016-07-29 15:13
Since `*/*` is the default accept should there be a check to see if this is the `req_mime` value and if it is set it?

Something like
```
values = values.map do |req_mime, quality|
   if req_mime == DEFAULT_ACCEPT
      match = 'text/html' # or DEFAULT_CONTENT_TYPE which is 'application/octet-stream'
   else
      match = available_mimes.find { |am| ::Rack::Mime.match?(am, req_mime) }
    end
    next unless match
    [match, quality]
end.compact
```

If this is a possible solution, would it be set as `text/html` or as rack's default `application/octet-stream`?

Any comments or ideas?

**Comment by bruz** [comment] 2016-07-29 17:12
Curious - I'd never looked at the accept header coming from old IE versions, but for IE8 I can confirm it's sending `image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, */*`, and that I'm also hitting that same error as you with a [Hanami 0.8.0 example app](https://github.com/bruz/bookshelf-delivery-example).

Your added check for `DEFAULT_FORMAT` seems like a good idea, but what do you think of setting the result to `configuration.default_request_format` in that case? That way it's configurable, but the default MIME type will be `text/html`.

**Comment by jodosha** [comment] 2016-08-09 10:43
@amccann1 Hi and thanks for reporting this problem. That supposed to be the expected purpose of `default_response_format`: to return the specified format when `HTTP_ACCEPT` is `*/*`. 😄 

So the attached PR should be merged. Thank you for that! 👍 

---

However, I don't understand one thing:

> Since IE8 has */* at the end of its HTTP_ACCEPT should it not also get :html?

You say "at the end", but the PR tests against `*/*`. It should theoretically work with a header that ends with `*/*`, see: https://github.com/hanami/controller/blob/717f0c2ee9c7938dfc170db08a8880c445401de6/test/action/format_test.rb#L54-L60

What's the header that IE8 sends? I'm trying to understand if we're missing something here. 😄

**Comment by amccann1** [comment] 2016-08-09 11:01
Hi @jodosha 
As bruz said above IE8 sends `image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, */*` 

I set the default to be `:jpeg` so I didnt want to send that through for the test so I only put `*/*`.

Now that I think on it the test you mentioned could work for this as well if you remove the `text/html` from the input header as that is the set default for `FormatController::Lookup.new`, the test should then prove that when a header is sent with no matching values it defaults.

**Comment by jodosha** [comment] 2016-08-09 11:12
@amccann1 Hey, thanks for the quick reply!

So in my understanding, IE8 sends that header to HTML resources? Eg. `/signup` would receive that header? This causes Hanami to understand that the browser wants a `:jpeg` format and tries to render `signup/new.jpeg.erb`, which doesn't exists and this condition causes an exception. Correct?

Of course we want that when IE8 hits `/signup` it would render the correct HTML template. But at this point my question is: how we can make this to happen, if there isn't any mention of HTML in this header? `image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, */*`

If we decide that if the header includes `*/*` we should rely on `default_response_format`, it's a dangerous assumption, because a browser can legitimately ask for a JPEG resource and including `*/*`. What do you think?

**Comment by amccann1** [comment] 2016-08-09 12:14
@jodosha 
I thought if the browser asks for JPEG then it would be weighed higher than the `default_response_format` in the value sort so it wouldn't be a problem or have I misunderstood how the works?

**Comment by bruz** [comment] 2016-08-09 18:59
@jodosha it seems like the ideal fix here would be to do content negotiation by going through the list of types in the accept header (sorted first by the `q` value specified, and then order listed), and picking the first one which the action supports. It seems like that's not really possible with `best_q_match` only providing a single MIME type to match against?

That being said, #170 fixes the IE8 issue, and I can't find a case where it fails but the current code doesn't also fail. For example, I tried a simple app where `default_response_format` is `:html`,  but it has an action with a `.json.erb` template. In both cases an accept header of `application/json, */*` fails, without #170 because it can't find a template with `ez` format (the one it happens to pick from all available mime types), and with it because it can't find an `html` one.

**Comment by jodosha** [comment] 2016-08-10 06:49
@bruz 

> it seems like the ideal fix here would be to do content negotiation by going through the list of types in the accept header (sorted first by the q value specified, and then order listed), and picking the first one which the action supports.

We pick the MIME Type that has more weight, this is the role of `best_q_match`. The handling of the corresponding format is delegated to other methods with high level abstraction.

> That being said, #170 fixes the IE8 issue, and I can't find a case where it fails but the current code doesn't also fail.

Great! Thank you @amccann1 and @bruz for this discussion. I'm gonna merge #170 right now! 👍

**Closed** 2016-08-10 06:50 UTC
Labels: bug
