### ISSUE TITLE
Helpers test suite not passing with controller master branch

### ISSUE THREAD

**Issue by TiteiKo** [hanami/controller#176] opened 2016-08-29 10:22 UTC
Hey all,

Just in case no one noticed yet, in the helpers repo, there's a test not passing anymore when pointing controller to the master branch: 

``` ruby
  1) Failure:
Form helper::form to update a resource::after a failed submission with blank values#test_0001_renders the form [/projects/helpers/test/integration/form_helper_test.rb:91]:
```

Basically, the params in which we dig inspects as:

``` ruby
#0.7.x
#<DeliveryParams:0x007fdc6c1bee00 @env={:delivery=>{"address"=>{"street"=>""}}}, @input={"delivery"=>{"address"=>{"street"=>""}}}, @result=#<Dry::Validation::Result output={:delivery=>{:address=>{:street=>""}}} messages={:delivery=>{:customer_id=>["is missing"], :address=>{:street=>["must be filled"]}}}>, @params={:delivery=>{:address=>{:street=>""}}}>

# master
#<DeliveryParams:0x007f9320c62d38 @env={:delivery=>{:address=>{:street=>nil}}}, @input={:delivery=>{:address=>{:street=>nil}}}, @result=#<Dry::Validation::Result output={:delivery=>{:address=>{:street=>nil}}} messages={:delivery=>{:customer_id=>["is missing"], :address=>{:street=>["must be filled"]}}}>, @params={:delivery=>{:address=>{:street=>nil}}}>
```

(delivery.address.street was "" and is now nil)

**Comment by cllns** [comment] 2016-08-30 14:00
Thanks for finding this @TiteiKo! Do you think the spec needs to be updated, or that this is an unplanned/bad regression? My intuition leads me to think it's the former, since we got rid of stringifying params.

**Comment by TiteiKo** [comment] 2016-08-30 14:04
Depends on rack, I guess... When a text field is empty, does rack send `""` or `nil` as a param?

If it's `""`, then the test is not written well (test/integration/form_helper_test.rb:83)

```ruby
# actual
        @params   = DeliveryParams.new(delivery: { address: { street: nil } })
# should be if rack sends ""
        @params   = DeliveryParams.new(delivery: { address: { street: '' } })
```

**Comment by jodosha** [comment] 2016-11-09 15:17
@TiteiKo I guess this can be closes because it was fixed by your PR https://github.com/hanami/helpers/pull/83

**Closed by jodosha** 2016-11-09 15:17 UTC

**Comment by TiteiKo** [comment] 2016-11-09 15:38
Yep, sorry I forgot to close this when I submitted the new one
