### ISSUE TITLE
Specify View in Controller

### ISSUE THREAD

**Issue by badoet** [hanami/controller#233] opened 2017-09-15 03:51 UTC
Currently it does the orders#index controller will automatically use orders/index view
can i change this?
so that orders#show and orders#index will both use orders/show view?

**Comment by jodosha** [comment] 2017-09-18 07:10
@badoet Hi, do you know you can specify a different template to render? http://hanamirb.org/guides/1.0/views/templates/#custom-template

Would this work for you?

**Comment by badoet** [comment] 2017-09-18 08:18
yeap i found that i can get the view to point to the same template. but sometime the template require some functions in the view. and this leads to code duplication. 
i need to copy the bunch of functions used in the templates across the different view.
so this solution is not ideal, i would say.

**Comment by beauby** [comment] 2017-09-18 08:18
@badoet You could define those methods in a module that you include in each view.

**Comment by badoet** [comment] 2017-09-18 08:23
true enough. im just checking if anyone feel the same way as i do on the need for more flexibility for this. because it will affect your code structures as well and potentially create less codes to solve this issue. 
if majority think this is a non-issue, i would oblige

**Comment by cllns** [comment] 2017-09-18 16:49
Yea, I think a very popular use-case for this would be `update` using the `edit` view, and `create` using the `new` view (both gender redirect on success, but render a view when there's a problem).

**Comment by jodosha** [comment] 2018-04-05 13:01
I'm closing this as not immediately actionable.

---

The issue is marked "for future consideration" because this is an important aspect of the request/response cycle, **especially** for failed form submissions.

I resisted the temptation to design actions with `if`/`elsif`/`else` conditionals. Right now the framework decides which view to render. I really love to see a kind of pattern matching implemented for actions, which ideally is able to match the result of an interactor.

**Closed by jodosha** 2018-04-05 13:01 UTC
Labels: discussion, for-future-consideration
